---
- name: Install HTTPD
  hosts: 127.0.0.1
  become: yes
  remote_user: cloud-user
  tasks:
  - name: YUM HTTPD
    yum: name=httpd state=latest
  - name: Service HTTD
    service: name=httpd state=started
